// League data with colors
export const leagues = [
    {
      id: "soccer",
      name: "All Leagues",
      format: "subreddit",
      color: "text-emerald-400",
      bgColor: "bg-emerald-400",
      gradientColor: "52,211,153",
      borderColor: "border-emerald-400/50",
      fromColor: "from-emerald-400/10",
      toColor: "to-emerald-400/10",
      logo: null,
    },
    {
      id: "premierleague",
      name: "Premier League",
      format: "league",
      color: "text-fuchsia-500",
      bgColor: "bg-fuchsia-500",
      gradientColor: "217,70,239",
      borderColor: "border-fuchsia-500/50",
      fromColor: "from-fuchsia-500/10",
      toColor: "to-fuchsia-500/10",
      logo: "/img/prem.png",
    },
    {
      id: "laliga",
      name: "La Liga",
      format: "league",
      color: "text-red-500",
      bgColor: "bg-red-500",
      gradientColor: "255,99,99",
      borderColor: "border-red-500/50",
      fromColor: "from-red-500/5",
      toColor: "to-red-500/5",
      logo: "/img/la-liga-new.webp",
    },
    {
      id: "seriea",
      name: "Serie A",
      format: "league",
      color: "text-blue-500",
      bgColor: "bg-blue-500",
      gradientColor: "59,130,246",
      borderColor: "border-blue-500/50",
      fromColor: "from-blue-500/10",
      toColor: "to-blue-500/5",
      logo: "/img/serie-a.png",
    },
    {
      id: "bundesliga",
      name: "Bundesliga",
      format: "league",
      color: "text-rose-500",
      bgColor: "bg-rose-500",
      gradientColor: "244,63,94",
      borderColor: "border-rose-500/50",
      fromColor: "from-rose-500/10",
      toColor: "to-rose-500/10",
      logo: "/img/bundesliga.jpeg",
    },
    {
      id: "ligue1",
      name: "Ligue 1",
      format: "league",
      color: "text-lime-500",
      bgColor: "bg-lime-500",
      gradientColor: "132,204,22",
      borderColor: "border-lime-500/50",
      fromColor: "from-lime-500/10",
      toColor: "to-lime-500/5",
      logo: "/img/Ligue1_logo.png",
    },
    {
      id: "mls",
      name: "MLS",
      format: "league",
      color: "text-violet-500",
      bgColor: "bg-violet-500",
      gradientColor: "139,92,246",
      borderColor: "border-violet-500/50",
      fromColor: "from-violet-500 bg-opacity-0",
      toColor: "to-violet-500/5",
      logo: "/img/MLS.png",
    },
  ]